package com.smzdm.basemapper;


import com.smzdm.pojo.ArticleJson;

import java.util.List;

public interface ArticleJsonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_json
     *
     * @mbg.generated Fri Jan 26 22:57:38 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_json
     *
     * @mbg.generated Fri Jan 26 22:57:38 CST 2018
     */
    int insert(ArticleJson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_json
     *
     * @mbg.generated Fri Jan 26 22:57:38 CST 2018
     */
    ArticleJson selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_json
     *
     * @mbg.generated Fri Jan 26 22:57:38 CST 2018
     */
    List<ArticleJson> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_json
     *
     * @mbg.generated Fri Jan 26 22:57:38 CST 2018
     */
    int updateByPrimaryKey(ArticleJson record);
}