package com.smzdm.basemapper;

import com.smzdm.pojo.Article;
import org.apache.ibatis.annotations.Delete;

import java.util.List;


public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article
     *
     * @mbg.generated Sat Jan 20 22:48:34 CST 2018
     */
    int deleteByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article
     *
     * @mbg.generated Sat Jan 20 22:48:34 CST 2018
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article
     *
     * @mbg.generated Sat Jan 20 22:48:34 CST 2018
     */
    Article selectByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article
     *
     * @mbg.generated Sat Jan 20 22:48:34 CST 2018
     */
    List<Article> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article
     *
     * @mbg.generated Sat Jan 20 22:48:34 CST 2018
     */
    int updateByPrimaryKey(Article record);

    void deleteByIDList(List<Integer> ids);
}