server:
  port: 17676
spring:
  redis:
    database: 0
    host: 192.168.2.233
    password: redispwd
    port: 6379
  datasource:
    url: jdbc:postgresql://192.168.2.233:5432/smzdm
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: rootpwd
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.smzdm.typehandler
logging:
  level:
    root: info
    com.ibatis: TRACE
    com.smzdm: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
custom:
  category-key: categoryList
  search-url: "https://api.smzdm.com/v1/list?keyword={0}&type={1}&order=time&limit=100&offset={2}"