server:
  port: 17676
spring:
  redis:
    database: 0
    host: 192.168.2.233
    password: redispwd
    port: 6379
  datasource:
    url: jdbc:postgresql://192.168.2.233:5432/smzdm
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: rootpwd
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.smzdm.typehandler
logging:
  level:
    root: info
    com.ibatis: TRACE
    com.smzdm: debug
  path: /home/logs/spider/
  file: spider.log
custom:
  turn: home:turn
  unknown-category: unknown:category