server:
  port: 17676
spring:
  redis:
    database: 0
    host: 192.168.2.233
    password: redispwd
    port: 6379
  datasource:
    url: jdbc:postgresql://192.168.2.233:5432/smzdm
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: rootpwd
mybatis:
  mapper-locations: classpath:basemapper/*.xml,classpath:extramapper/*.xml
  type-handlers-package: com.smzdm.typehandler
spider:
  home-url: http://www.smzdm.com/homepage/json_more
  discovery-url: http://faxian.smzdm.com/json_more?page=2,http://faxian.smzdm.com/json_more?page=1
  hot-url: http://faxian.smzdm.com/json_more?filter=h3s0t0f0c0&page=5,http://faxian.smzdm.com/json_more?filter=h3s0t0f0c0&page=4,http://faxian.smzdm
  .com/json_more?filter=h3s0t0f0c0&page=3,http://faxian.smzdm.com/json_more?filter=h3s0t0f0c0&page=2,http://faxian.smzdm.com/json_more?filter=h3s0t0f0c0&page=1