server:
  port: 17676
spring:
  redis:
    database: 0
    port: 6379
  datasource:
    url: jdbc:postgresql://192.168.2.233:5432/smzdm
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: rootpwd
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.smzdm.typehandler
logging:
  level:
    root: info
    com.ibatis: TRACE
    com.smzdm: debug
  path: /home/logs/spider/
  file: spider.log
custom:
  turn: home:turn
  unknown-category: unknown:category
  category-key: categoryList
  sub-prefix: "sub:"
  access-token-key: saa:access-token
  openId: oVJJCvx28HDsflYiPF-EwKsYeOJ8
  url-prefix: "https://www.smzdm.com/p/"
  notice-url: "https://api.weixin.qq.com/cgi-bin/message/template/send?access_token="
  ip-url: "https://api.ip.sb/ip"
  ip-key: home-ip
redis-config:
  expired-topic: __keyevent@0__:expired
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 100
  keep-alive-seconds: 60
  thread-name-prefix: redis